export const forms = [
  {
    id: '4',
    riskCategory: 'commercial-and-business',
    titleFr: 'APRIL Canada - E et O Fabricants et fournisseurs',
    titleEn: 'APRIL Canada - E and O Manufacturers and suppliers',
    linkFr: null,
    linkEn: 'APRIL-Canada-%E2%80%93-EandO-Manufacturers-and-Suppliers-2.doc',
    icon: 'business.svg',
  },
  {
    id: '5',
    riskCategory: 'commercial-and-business',
    titleFr: 'APRIL Canada - E et O Divers',
    titleEn: 'APRIL Canada - E and O Miscellaneous',
    linkFr: null,
    linkEn: 'APRIL-Canada-%E2%80%93-Miscellaneous-EO.doc',
    icon: 'business.svg',
  },
  {
    id: '6',
    riskCategory: 'commercial-and-business',
    titleFr: 'APRIL Canada - Fabricants et distributeurs d’emballages',
    titleEn: 'APRIL Canada - Package manufacturers and distributors',
    linkFr: null,
    linkEn:
      'APRIL-Canada-%E2%80%93-Package_Manufacturers-and-Distributors-1.docx',
    icon: 'business.svg',
  },
  {
    id: '7',
    riskCategory: 'commercial-and-business',
    titleFr: 'Ingénieurs architectes',
    titleEn: 'Architects engineers',
    linkFr: null,
    linkEn: 'APRIL-Canada-Architects-Engineers.doc',
    icon: 'business.svg',
  },
  {
    id: '8',
    riskCategory: 'commercial-and-business',
    titleFr: 'Renouvellement commercial',
    titleEn: 'Commercial renewal',
    linkFr: 'APRIL-Canada-Renouvellement-dAssurance-Commerciale-1.docx',
    linkEn: 'APRIL-Canada-Commercial-Renewal-Short-form.docx',
    icon: 'business.svg',
  },
  {
    id: '9',
    riskCategory: 'commercial-and-business',
    titleFr: 'Renouvellement responsabilité civile',
    titleEn: 'Comprehensive general liability renewal',
    linkFr: 'APRIL-Canada-Responsabilit%C3%A9-Civile-G%C3%A9n%C3%A9rale-1.docx',
    linkEn:
      'APRIL-Canada-%E2%80%93-Comprehensive-General-Liability-short-form.doc',
    icon: 'business.svg',
  },
  {
    id: '10',
    riskCategory: 'commercial-and-business',
    titleFr: 'Responsabilité civil générale',
    titleEn: 'Comprehensive general liability',
    linkFr: null,
    linkEn:
      'APRIL-Canada-%E2%80%93-Comprehensive-General-Liability-short-form.doc',
    icon: 'business.svg',
  },
  {
    id: '11',
    riskCategory: 'commercial-and-business',
    titleFr: 'Cours de construction et de rénovation',
    titleEn: 'Course of construction and renovation application',
    linkFr: null,
    linkEn: 'APRIL-Canada-COC-and-Wrap-Up-application.docx',
    icon: 'business.svg',
  },
  {
    id: '12',
    riskCategory: 'commercial-and-business',
    titleFr: 'Cyber (énoncé des faits et critères d’admissibilité)',
    titleEn: 'Cyber (statement of fact and eligibility criterias)',
    linkFr: null,
    linkEn: 'APRIL-Canada_Cyber-Statement-and-list-of-Eligibility-Criteria.pdf',
    icon: 'business.svg',
  },
  {
    id: '13',
    riskCategory: 'commercial-and-business',
    titleFr: 'Administrateurs et dirigeants',
    titleEn: 'Directors and officers',
    linkFr: null,
    linkEn: 'April-Canada-D-and-O-Application.docx',
    icon: 'business.svg',
  },
  {
    id: '14',
    riskCategory: 'commercial-and-business',
    titleFr: 'Renouvellement E et O',
    titleEn: 'E and O renewal',
    linkFr: 'APRIL-Canada-EO-Renouvellement-1.docx',
    linkEn: 'APRIL-Canada-EO-Renewal-application.docx',
    icon: 'business.svg',
  },
  {
    id: '15',
    riskCategory: 'commercial-and-business',
    titleFr: 'Marchand d’œuvres d’art',
    titleEn: 'Fine Art dealer',
    linkFr: null,
    linkEn: 'APRIL-Canada-Fine-Art-Dealer-Proposal.docx',
    icon: 'business.svg',
  },
  {
    id: '16',
    riskCategory: 'commercial-and-business',
    titleFr: 'Hospitalité',
    titleEn: 'Hospitality',
    linkFr: null,
    linkEn: 'APP-Liq-Bar-Restaurant-APRIL-V2.pdf',
    icon: 'business.svg',
  },
  {
    id: '17',
    riskCategory: 'commercial-and-business',
    titleFr: 'Bijoutier',
    titleEn: "Jeweller's block",
    linkFr: null,
    linkEn: 'APRIL-Canada-Jeweller-Block-App.docx',
    icon: 'business.svg',
  },
  {
    id: '18',
    riskCategory: 'commercial-and-business',
    titleFr: 'Faute médicale - médecine alternative',
    titleEn: 'Medical malpractice - alternative healing',
    linkFr: null,
    linkEn: 'APRIL-Canada-%E2%80%93-MedMal-Alternative-Healing-v2.docx',
    icon: 'business.svg',
  },
  {
    id: '19',
    riskCategory: 'commercial-and-business',
    titleFr: 'Renouvellement Faute médicale - médecine alternative',
    titleEn: 'Medical malpractice - alternative healing renewal',
    linkFr: null,
    linkEn:
      'APRIL-Canada-%E2%80%93-MedMal-Alternative-Healing-Renewal-v3-1.docx',
    icon: 'business.svg',
  },
  {
    id: '20',
    riskCategory: 'commercial-and-business',
    titleFr: 'Faute médicale - services médicaux',
    titleEn: 'Medical malpractice - medical services',
    linkFr: null,
    linkEn: 'APRIL-Canada-%E2%80%93-MedMal-Medical-Services.docx',
    icon: 'business.svg',
  },
  {
    id: '21',
    riskCategory: 'commercial-and-business',
    titleFr: 'Renouvellement faute médicale - services médicaux',
    titleEn: 'Medical malpractice - medical services renewal',
    linkFr: null,
    linkEn: 'APRIL-Canada-%E2%80%93-MedMal-Medical-Services-Renewal-v3.docx',
    icon: 'business.svg',
  },
  {
    id: '22',
    riskCategory: 'commercial-and-business',
    titleFr: 'Faute médicale - supplément sur les propriétés mobilière',
    titleEn: 'Medical malpractice - property supplement',
    linkFr: null,
    linkEn: 'Property-supplement.docx',
    icon: 'business.svg',
  },
  {
    id: '23',
    riskCategory: 'commercial-and-business',
    titleFr: 'Faute médicale - coiffeur et spa',
    titleEn: 'Medical malpractice - salon and spa',
    linkFr: null,
    linkEn: 'APRIL-Canada-%E2%80%93-MedMal-Salon-or-Spa-v2.docx',
    icon: 'business.svg',
  },
  {
    id: '24',
    riskCategory: 'commercial-and-business',
    titleFr: 'Renouvellement faute médicale - coiffeur et spa',
    titleEn: 'Medical malpractice - salon and spa renewal',
    linkFr: null,
    linkEn: 'APRIL-Canada-%E2%80%93-MedMal-Salon-or-Spa-Renewal-v3.docx',
    icon: 'business.svg',
  },
  {
    id: '25',
    riskCategory: 'commercial-and-business',
    titleFr: 'Articles personnels',
    titleEn: 'Personal articles',
    linkFr: null,
    linkEn: 'Personal-Articles-Floater-Application-1117.docx',
    icon: 'business.svg',
  },
  {
    id: '26',
    riskCategory: 'commercial-and-business',
    titleFr: 'Rappel de produit - formulaire de proposition',
    titleEn: 'Product recall - application form',
    linkFr: null,
    linkEn: 'APRIL-Canada-%E2%80%93-Product-Recall-Application-form.docx.docx',
    icon: 'business.svg',
  },
  {
    id: '27',
    riskCategory: 'commercial-and-business',
    titleFr: 'Rappel de produit - formulaire de soumission',
    titleEn: 'Product recall - indication form',
    linkFr: null,
    linkEn: 'APRIL-Canada-%E2%80%93-Product-Recall-Indication-form.docx.docx',
    icon: 'business.svg',
  },
  {
    id: '28',
    riskCategory: 'commercial-and-business',
    titleFr: 'Location commerciale',
    titleEn: 'Commercial rental',
    linkFr: null,
    linkEn: 'Commercial-Rental.pdf',
    icon: 'business.svg',
  },
  {
    id: '29',
    riskCategory: 'commercial-and-business',
    titleFr: 'Petit COC',
    titleEn: 'Small COC',
    linkFr: null,
    linkEn: 'APRIL-Canada-Small-COC-Application.docx',
    icon: 'business.svg',
  },
  {
    id: '30',
    riskCategory: 'commercial-and-business',
    titleFr: 'Rénovations mineures',
    titleEn: 'Small renovations',
    linkFr: null,
    linkEn: 'APRIL-Canada-Small-Renovations-Application.docx',
    icon: 'business.svg',
  },
  {
    id: '33',
    riskCategory: 'commercial-and-business',
    titleFr: 'Responsabilité civile complémentaire et excédentaire',
    titleEn: 'Umbrella and Excess insurance',
    linkFr: 'Umbrella-and-Excess-Application-1016-FV.docx',
    linkEn: 'APRIL-Canada-Umbrella-and-Excess-Application.docx',
    icon: 'business.svg',
  },
  {
    id: '34',
    riskCategory: 'commercial-and-business',
    titleFr: 'Immeuble commercial vacant',
    titleEn: 'Vacant commercial building',
    linkFr: null,
    linkEn: 'APRIL-Canada-Commercial-Vacant-Building.docx',
    icon: 'business.svg',
  },
  {
    id: '35',
    riskCategory: 'commercial-and-business',
    titleFr: 'Questionnaire entrepreneur',
    titleEn: 'Contractor',
    linkFr: 'Questionnaire-Entrepreneur-Fr..docx',
    linkEn: 'Questionnaire-Entrepreneur-Ang..docx',
    icon: 'business.svg',
  },
  {
    id: '36',
    riskCategory: 'commercial-and-business',
    titleFr: 'Cyber',
    titleEn: 'Cyber',
    linkFr: 'Cyber-Application-Form-1.pdf',
    linkEn: 'Cyber-Application-Form-1.pdf',
    icon: 'business.svg',
  },
  {
    id: '37',
    riskCategory: 'residential',
    titleFr: 'AirBnB - location à court terme',
    titleEn: 'AirBnB - short term rental',
    linkFr: 'Questionnaire_Location-Court-Terme.doc',
    linkEn: 'APRIL-Canada-Airbnb_Short-term-rentals.doc',
    icon: 'residential.svg',
  },
  {
    id: '38',
    riskCategory: 'residential',
    titleFr: "Assurance habitation - présence d'un chien",
    titleEn: 'APRIL Canada - Dog questionnaire',
    linkFr: 'APRIL-Canada-Questionnaire_Pr%C3%A9sence-dun-chien.doc',
    linkEn: 'APRIL-Canada-Dog-Questionnaire.docx',
    icon: 'residential.svg',
  },
  {
    id: '39',
    riskCategory: 'residential',
    titleFr: 'Aquatrip - guide pour les courtiers',
    titleEn: 'Aquatrip - guide for brokers',
    linkFr: null,
    linkEn: 'Flyer-Aquatrip.pdf',
    icon: 'residential.svg',
  },
  {
    id: '41',
    riskCategory: 'residential',
    titleFr: 'Réservoire de mazoute',
    titleEn: 'Fuel oil tank',
    linkFr: 'QUESTIONNAIRE-SUR-LE-R%C3%89SERVOIR-%C3%80-MAZOUT.pdf',
    linkEn: 'Residential-Fuel-Oil-Tank-Questionnaire.pdf',
    icon: 'residential.svg',
  },
  {
    id: '42',
    riskCategory: 'residential',
    titleFr: 'Rénovations mineures',
    titleEn: 'Minor renovations',
    linkFr: 'Questionnaire_R%C3%A9novations-mineures-1.doc',
    linkEn: 'APRIL-Canada-Minor-renovations-questionnaire.docx',
    icon: 'residential.svg',
  },
  {
    id: '43',
    riskCategory: 'residential',
    titleFr: 'Hypothèque',
    titleEn: 'Mortgages',
    linkFr: null,
    linkEn: 'APRIL-Canada-Mortgages.doc',
    icon: 'residential.svg',
  },
  {
    id: '44',
    riskCategory: 'residential',
    titleFr: 'Assuré résident hors de la province ou du pays',
    titleEn: 'Out of province or country',
    linkFr: 'APRIL-Canada-Questionnaire_Hors-de-la-province-ou-du-pays.doc',
    linkEn: 'APRIL-Canada-Out-of-Province-or-Country-Insured.doc',
    icon: 'residential.svg',
  },
  {
    id: '45',
    riskCategory: 'residential',
    titleFr: 'Location - liste de contrôle',
    titleEn: 'Rental check list',
    linkFr: null,
    linkEn: 'APRIL-Canada-Rental-Checklist.docx',
    icon: 'residential.svg',
  },
  {
    id: '46',
    riskCategory: 'residential',
    titleFr: 'Maison vacante',
    titleEn: 'Vacant home',
    linkFr: null,
    linkEn: 'APRIL-Canada-Vacant-Application-Oct-2017.docx',
    icon: 'residential.svg',
  },
  {
    id: '47',
    riskCategory: 'residential',
    titleFr: 'Poèle à bois',
    titleEn: 'Woodstove',
    linkFr: 'APRIL-Canada-Questionnaire-po%C3%AAle-%C3%A0-bois.doc',
    linkEn: 'CSIO-Woodstove-Questionnaire.pdf',
    icon: 'residential.svg',
  },
  {
    id: '48',
    riskCategory: 'residential',
    titleFr: 'Résidentiel',
    titleEn: 'Residential',
    linkFr: null,
    linkEn: 'APRIL-Canada-Residential-Application.docx',
    icon: 'residential.svg',
  },
  {
    id: '49',
    riskCategory: 'residential',
    titleFr: 'Quais - norme de souscriptions',
    titleEn: 'Docks - underwritting norms',
    linkFr: null,
    linkEn: 'Normes-de-souscription-Quais-Interactif.pdf',
    icon: 'residential.svg',
  },
  {
    id: '50',
    riskCategory: 'residential',
    titleFr: 'Automobile - Intact',
    titleEn: 'Automobile - Intact',
    linkFr: 'Proposition-auto-Intact-fran%C3%A7ais.dotx',
    linkEn: 'Proposition-auto-Intact-anglais.dotx',
    icon: 'residential.svg',
  },
  {
    id: '51',
    riskCategory: 'residential',
    titleFr: 'Intact Prestige',
    titleEn: 'Intact Prestige',
    linkFr: 'Proposition-Intact-Prestige-Fran%C3%A7ais.pdf',
    linkEn: 'Proposition-Intact-Prestige-Anglais.pdf',
    icon: 'residential.svg',
  },
  {
    id: '52',
    riskCategory: 'residential',
    titleFr: 'Poèle à bois - questionnaire',
    titleEn: 'Woodstove - questionnaire',
    linkFr: 'CSIO-Woodstove-Questionnaire-EN-1.pdf',
    linkEn: 'CSIO-Woodstove-Questionnaire-EN-1.pdf',
    icon: 'residential.svg',
  },
  {
    id: '53',
    riskCategory: 'trucking-and-towing',
    titleFr: 'Responsabilité civile',
    titleEn: 'Comprehensive general liability',
    linkFr: null,
    linkEn: 'CSIO-Woodstove-Questionnaire-EN-1.pdf',
    icon: 'commercial-automobile.svg',
  },
  {
    id: '54',
    riskCategory: 'trucking-and-towing',
    titleFr: 'Responsabilité civile - renouvellement',
    titleEn: 'Comprehensive general liability - renewal',
    linkFr: null,
    linkEn:
      'APRIL-Canada-%E2%80%93-Comprehensive-General-Liability-short-form.doc',
    icon: 'commercial-automobile.svg',
  },
  {
    id: '55',
    riskCategory: 'trucking-and-towing',
    titleFr: 'Contingence',
    titleEn: 'Contingency',
    linkFr: null,
    linkEn: 'APRIL-Canada-Contingency-EN.doc',
    icon: 'commercial-automobile.svg',
  },
  {
    id: '56',
    riskCategory: 'trucking-and-towing',
    titleFr: 'Transport de marchandise dangereuse',
    titleEn: 'Dangerous goods transport',
    linkFr: null,
    linkEn: 'APRIL-Canada-Transport-de-MD-DG-Transport.doc',
    icon: 'commercial-automobile.svg',
  },
  {
    id: '57',
    riskCategory: 'trucking-and-towing',
    titleFr: 'Réservoire de mazoute',
    titleEn: 'Fuel oil tank',
    linkFr: null,
    linkEn: 'Residential-Fuel-Oil-Tank-Questionnaire.pdf',
    icon: 'commercial-automobile.svg',
  },
  {
    id: '58',
    riskCategory: 'commercial-marine',
    titleFr: 'Concessionnaire de bateaux',
    titleEn: 'Boat dealers',
    linkFr: 'APRIL-Canada-Concessionnaire-Bateaux.docx',
    linkEn: 'APRIL-Canada-Boat-Dealers.docx',
    icon: 'commercial-marine.svg',
  },
  {
    id: '59',
    riskCategory: 'commercial-marine',
    titleFr: 'Chantier naval - risque unique',
    titleEn: 'Builder risk single',
    linkFr: 'APRIL-Canada-Chantier-Naval-Risque-Unique.docx',
    linkEn: 'APRIL-Canada-Builder-Risk-Single.docx',
    icon: 'commercial-marine.svg',
  },
  {
    id: '60',
    riskCategory: 'commercial-marine',
    titleFr: 'Risque pour le constructeur - chantier naval',
    titleEn: 'Builder risk yard',
    linkFr: 'APRIL-Canada-Chantier-Naval.docx',
    linkEn: 'APRIL-Canada-Builder-Risk-Yard.docx',
    icon: 'commercial-marine.svg',
  },
  {
    id: '61',
    riskCategory: 'commercial-marine',
    titleFr: 'Exploitant de marina',
    titleEn: 'Marina operator',
    linkFr: 'APRIL-Canada-Marina.docx',
    linkEn: 'APRIL-Canada-Marina-Operator.docx',
    icon: 'commercial-marine.svg',
  },
  {
    id: '62',
    riskCategory: 'commercial-marine',
    titleFr: 'Services de fret',
    titleEn: 'Freight service',
    linkFr: 'Freight-Services-Application.pdf',
    linkEn: 'Freight-Services-Application.pdf',
    icon: 'commercial-marine.svg',
  },
  {
    id: '63',
    riskCategory: 'commercial-marine',
    titleFr: 'Coque et PI',
    titleEn: 'Hull and PI',
    linkFr: 'Hull-and-PI-French-July-2015.pdf',
    linkEn: 'Hull-and-PI-English-2020.pdf',
    icon: 'commercial-marine.svg',
  },
  {
    id: '64',
    riskCategory: 'commercial-marine',
    titleFr: 'Stock et transit',
    titleEn: 'Stock throughput',
    linkFr: 'April-StockThroughput-App-2020.xlsx',
    linkEn: 'April-StockThroughput-App-2020.xlsx',
    icon: 'commercial-marine.svg',
  },
  {
    id: '65',
    riskCategory: 'commercial-marine',
    titleFr: 'Métiers maritimes',
    titleEn: 'Marine trades',
    linkFr: 'Marine-Trades-2020.xlsx',
    linkEn: 'Marine-Trades-2020.xlsx',
    icon: 'commercial-marine.svg',
  },
  {
    id: '66',
    riskCategory: 'trucking-and-towing',
    titleFr: 'Camion-moteur cargaison',
    titleEn: 'Motor truck cargo',
    linkFr: null,
    linkEn: 'APRIL-Motor-Truck-Cargo-MTC-2.pdf',
    icon: 'commercial-automobile.svg',
  },
  {
    id: '67',
    riskCategory: 'automobile',
    titleFr: 'Automibile commerciale',
    titleEn: 'Commercial automobile',
    linkFr: null,
    linkEn: 'APRIL-Canada-Commercial-Automobile-EN.doc',
    icon: 'automobile.svg',
  },
  {
    id: '68',
    riskCategory: 'automobile',
    titleFr: 'Resposabilité civile',
    titleEn: 'Comprehensive general liability',
    linkFr: null,
    linkEn: 'APRIL-Canada-Commercial-Automobile-EN.doc',
    icon: 'automobile.svg',
  },
  {
    id: '69',
    riskCategory: 'automobile',
    titleFr: 'Contingente',
    titleEn: 'Contingente',
    linkFr: null,
    linkEn: 'Contingente-Franc%CC%A7ais-1.docx',
    icon: 'automobile.svg',
  },
  {
    id: '70',
    riskCategory: 'automobile',
    titleFr: 'Garagiste/Ferrailleurs',
    titleEn: 'Garagiste/Recyclers',
    linkFr: null,
    linkEn: 'Garagistes-Recycleurs-Garagists-Recyclers.doc',
    icon: 'automobile.svg',
  },
  {
    id: '71',
    riskCategory: 'other-commercial',
    titleFr: 'April Canada - E et O fabricants et fournisseurs',
    titleEn: 'April Canada - E and O manufacturers and suppliers',
    linkFr: null,
    linkEn: 'APRIL-Canada-%E2%80%93-EandO-Manufacturers-and-Suppliers-2.doc',
    icon: 'other-commercial.svg',
  },
  {
    id: '72',
    riskCategory: 'other-commercial',
    titleFr: 'April Canada - Divers E et O',
    titleEn: 'April Canada - Miscellaneous E and O',
    linkFr: null,
    linkEn: 'APRIL-Canada-%E2%80%93-Miscellaneous-EO.doc',
    icon: 'other-commercial.svg',
  },
  {
    id: '73',
    riskCategory: 'other-commercial',
    titleFr: 'April-Canada - Fabricants et distributeurs de paquets',
    titleEn: 'April-Canada - Package manufacturers and distributers',
    linkFr: null,
    linkEn:
      'APRIL-Canada-%E2%80%93-Package_Manufacturers-and-Distributors-1.docx',
    icon: 'other-commercial.svg',
  },
  {
    id: '74',
    riskCategory: 'other-commercial',
    titleFr: 'Données et cyberassurance',
    titleEn: 'Data and cyber insurance',
    linkFr: null,
    linkEn: 'APRIL-Canada_DataCyber-Application-2.docx',
    icon: 'other-commercial.svg',
  },
  {
    id: '75',
    riskCategory: 'other-commercial',
    titleFr: 'Faute médicale - médecine alternative',
    titleEn: 'Medical malpractice - alternative healing',
    linkFr: null,
    linkEn: 'APRIL-Canada-%E2%80%93-MedMal-Alternative-Healing-v2.docx',
    icon: 'other-commercial.svg',
  },
  {
    id: '76',
    riskCategory: 'other-commercial',
    titleFr: 'Faute médicale - service',
    titleEn: 'Medical malpractice - services',
    linkFr: null,
    linkEn: 'APRIL-Canada-%E2%80%93-MedMal-Medical-Services.docx',
    icon: 'other-commercial.svg',
  },
  {
    id: '77',
    riskCategory: 'other-commercial',
    titleFr: 'Faute médicale - supplément sur les propriétés mobilière',
    titleEn: 'Medical malpractice - property supplement',
    linkFr: null,
    linkEn: 'Property-supplement.docx',
    icon: 'other-commercial.svg',
  },
  {
    id: '78',
    riskCategory: 'other-commercial',
    titleFr: 'Faute médicale - coiffeur et spa',
    titleEn: 'Medical malpractice - salon and spa',
    linkFr: null,
    linkEn: 'APRIL-Canada-%E2%80%93-MedMal-Salon-or-Spa-v2.docx',
    icon: 'other-commercial.svg',
  },
  // {
  //   id: '79',
  //   riskCategory: 'commercial-and-business',
  //   titleFr: 'APRIL Canada - Petit COC',
  //   titleEn: 'APRIL Canada - Small COC',
  //   linkFr: null,
  //   linkEn: null,
  //   icon: 'business.svg',
  // },
  {
    id: '81',
    riskCategory: 'commercial-and-business',
    titleFr: 'Demande de soumission en participation',
    titleEn: 'Request for participation',
    linkFr: 'APRIL-Canada-Demande-de-Soumission-en-participation-1.docx',
    linkEn: null,
    icon: 'business.svg',
  },
  {
    id: '82',
    riskCategory: 'commercial-and-business',
    titleFr: 'Toiture renouvellement',
    titleEn: 'Roofing renewal',
    linkFr:
      'APRIL-Canada-Questionnaire-renouvellement-RC-entrepreneur-en-toiture.docx',
    linkEn: null,
    icon: 'business.svg',
  },
  {
    id: '86',
    riskCategory: 'commercial-and-business',
    titleFr: 'Toiture - responsabilité civile générale',
    titleEn: 'Roofing - comprehensive general liability',
    linkFr:
      'APRIL-Canada-Proposition-de-responsabilit%C3%A9-civile-entrepreneur-en-toiture-2.docx',
    linkEn: null,
    icon: 'business.svg',
  },
  {
    id: '87',
    riskCategory: 'commercial-and-business',
    titleFr: 'COC et wrap up - rénovation majeures',
    titleEn: 'COC and wrap up - major renovation',
    linkFr:
      'COC-and-Wrap-Up-application-R%C3%A9novations-majeures-1016-FV.docx',
    linkEn: null,
    icon: 'business.svg',
  },
  {
    id: '89',
    riskCategory: 'commercial-and-business',
    titleFr:
      'Responsabilité civile complémentaire et excédentaire des entreprises',
    titleEn: 'Umbrella and excess liability - business',
    linkFr:
      'APRIL-Canada-Responsabilit%C3%A9-Civile-Compl%C3%A9mentaire-et-Exc%C3%A9dentaire-des-Entreprises-1016-1.docx',
    linkEn: null,
    icon: 'business.svg',
  },
  {
    id: '90',
    riskCategory: 'commercial-and-business',
    titleFr: 'Cautionnement RBQ',
    titleEn: 'RBQ Bond',
    linkFr: 'APRIL-Proposition-simplifi%C3%A9e.pdf',
    linkEn: null,
    icon: 'business.svg',
  },
  {
    id: '91',
    riskCategory: 'residential',
    titleFr: 'Bâtiment vacant ou innocupé',
    titleEn: 'Vacant building',
    linkFr:
      'APRIL-Canada-Batiment-Vacant-ou-Inoccupe-Vacant_Unoccupied-Building.docx',
    linkEn: null,
    icon: 'residential.svg',
  },
  {
    id: '92',
    riskCategory: 'residential',
    titleFr: 'Questionnaire plumitif et faillite',
    titleEn: 'Criminal record and brankruptcy questionnaire',
    linkFr: 'APRIL-Canada-Questionnaire_Plumitif-Faillite.doc',
    linkEn: null,
    icon: 'residential.svg',
  },
  {
    id: '94',
    riskCategory: 'residential',
    titleFr: 'Questionnaire résidence louée',
    titleEn: 'Rented dwelling questionnaire',
    linkFr: 'Questionnaire_R%C3%A9sidence-Lou%C3%A9e.docx',
    linkEn: null,
    icon: 'residential.svg',
  },
  {
    id: '95',
    riskCategory: 'residential',
    titleFr: 'Questionnaire créancier',
    titleEn: 'Creditors questionnaire',
    linkFr: 'Questionnaire_Cr%C3%A9anciers.doc',
    linkEn: null,
    icon: 'residential.svg',
  },
  {
    id: '96',
    riskCategory: 'residential',
    titleFr: 'Proposition sous standard',
    titleEn: 'Substandard application',
    linkFr: 'APRIL-Canada-Proposition-Re%CC%81sidentielle.docx',
    linkEn: null,
    icon: 'residential.svg',
  },
  {
    id: '97',
    riskCategory: 'residential',
    titleFr: 'Bâtiment vacant - questionnaire court',
    titleEn: 'Vacant building - short form',
    linkFr: 'Questionnaire_B%C3%A2timent-vacant_Court-1.doc',
    linkEn: null,
    icon: 'residential.svg',
  },
  {
    id: '99',
    riskCategory: 'trucking-and-towing',
    titleFr: 'Camionnage',
    titleEn: 'Trucking',
    linkFr: 'APRIL-Canada-Proposition-camionnage-Decembre-2019.doc',
    linkEn: null,
    icon: 'commercial-automobile.svg',
  },
  {
    id: '100',
    riskCategory: 'commercial-marine',
    titleFr: 'Réparateur de bateaux',
    titleEn: 'Boat repair',
    linkFr: 'APRIL-Canada-Reparateurs-Bateaux.docx',
    linkEn: null,
    icon: 'commercial-marine.svg',
  },
  {
    id: '102',
    riskCategory: 'commercial-marine',
    titleFr: 'Marine commerciale - responsabilité',
    titleEn: 'Commercial marine liability',
    linkFr: 'Commercial-Marine-Liability-application.pdf',
    linkEn: null,
    icon: 'commercial-marine.svg',
  },
  {
    id: '103',
    riskCategory: 'commercial-marine',
    titleFr: 'Débardeurs et opérateurs de terminaux',
    titleEn: 'Longshoremen and terminal operators',
    linkFr: 'APRIL-Canada-Debardeurs-Operateurs-Terminaux.docx',
    linkEn: null,
    icon: 'commercial-marine.svg',
  },
  {
    id: '104',
    riskCategory: 'trucking-and-towing',
    titleFr: 'Transport de produit réfrigérés',
    titleEn: 'Transport of refrigerated products',
    linkFr:
      'APRIL-Canada-Transport-de-Produits-Re%CC%81frige%CC%81re%CC%81s-1.docx',
    linkEn: null,
    icon: 'commercial-automobile.svg',
  },
];
